[env:m5stack-cores3]
platform = espressif32@6.3.2
board = esp32s3box
framework = arduino

board_build.arduino.memory_type = qio_qspi
board_build.f_flash = 80000000L
board_build.partitions = default_16MB.csv
board_build.filesystem = spiffs

monitor_speed = 115200
upload_speed = 115200

lib_deps =
    file://lib/StackChan-BSP
    bblanchon/ArduinoJson @ ^7
    https://github.com/ronron-gh/arduinoWebSockets.git#fix/max_data_size

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DREALTIME_API
    -DARDUINO_M5STACK_CORES3
    -DARDUINOJSON_STRING_LENGTH_SIZE=4
    -std=gnu++17

build_unflags =
    -std=gnu++11

lib_ldf_mode = deep

lib_ignore =
    IRremoteESP8266
    M5Unit-NFC
    M5UnitUnified
    M5Utility
    M5HAL